<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size: 150, 50
    background_normal: 'backgrnd-btn-color-2.png'
    background_down: 'backgrnd-btn-color.png'
    background_color: .88, .88, 0.88, 1

<CustomWidget>:
    CustButton:
        text: "Random"
        pos: root.x, 200

    CustButton:
        text: "Buttons"
        pos: 200, root.y

    CustButton:
        text: "Test"
        pos: 200, 400
            
